/*

 BASKET_SPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char basket_sprite[] =
{
  0x80,0xFF,0x80,0xFF,0x80,0xFF,0x40,0x7F,
  0x20,0x3F,0x10,0x1F,0x08,0x0F,0x07,0x07,
  0x01,0xFF,0x01,0xFF,0x01,0xFF,0x02,0xFE,
  0x04,0xFC,0x08,0xF8,0x10,0xF0,0xE0,0xE0
};

/* End of BASKET_SPRITE.C */
