/*

 BLOB.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 4

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define blobbo_spriteBank 0
/* Start of tile array. */
extern const const unsigned char blobbo_sprite[];
// extern unsigned char blobbo_sprite[];

/* End of BLOB.H */
