//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_nature_tiles_v2_H
#define METASPRITE_nature_tiles_v2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define nature_tiles_v2_TILE_ORIGIN 0
#define nature_tiles_v2_TILE_W 8
#define nature_tiles_v2_TILE_H 16
#define nature_tiles_v2_WIDTH 160
#define nature_tiles_v2_HEIGHT 144
#define nature_tiles_v2_TILE_COUNT 266
#define nature_tiles_v2_PALETTE_COUNT 1
#define nature_tiles_v2_COLORS_PER_PALETTE 4
#define nature_tiles_v2_TOTAL_COLORS 4
#define nature_tiles_v2_PIVOT_X 80
#define nature_tiles_v2_PIVOT_Y 72
#define nature_tiles_v2_PIVOT_W 160
#define nature_tiles_v2_PIVOT_H 144
extern const metasprite_t* const nature_tiles_v2_metasprites[1];

BANKREF_EXTERN(nature_tiles_v2)

extern const palette_color_t nature_tiles_v2_palettes[4];
extern const uint8_t nature_tiles_v2_tiles[4256];

#endif
