// This file was generated by img2gb, DO NOT EDIT

#ifndef _TITLE_SCREEN_TILESET_H
#define _TITLE_SCREEN_TILESET_H

extern const UINT8 title_screen_tiles[];
#define TITLE_SCREEN_TILESET_TILES_COUNT 141

#endif
