// This file was generated by img2gb, DO NOT EDIT

#ifndef _TITLE_SCREEN_TILEMAP_H
#define _TITLE_SCREEN_TILEMAP_H

extern const UINT8 title_screen_tilemap[];
#define TITLE_SCREEN_TILEMAP_WIDTH 20
#define TITLE_SCREEN_TILEMAP_HEIGHT 18


#endif
